add semver workflow dispatch

diff --git a/.github/workflows/build-and-package.yml b/.github/workflows/build-and-package.yml
--- a/.github/workflows/build-and-package.yml
+++ b/.github/workflows/build-and-package.yml
@@ -1,6 +1,11 @@
 name: .NET Build, Test, Package, and Report Coverage
 
 on: 
+  workflow_dispatch: 
+    inputs: 
+      semver:
+        required: true 
+        description: Provide the semver version to build and deploy the nuget package.  
   push: 
     branches: 
       - main
@@ -18,7 +23,17 @@ jobs:
         dotnet-version:
           - '5.0.x'
 
-    steps: 
+    steps:
+      - name: Check semver format
+        id: check-semver
+        if: github.event_name == 'workflow_dispatch'
+        run: |
+          semver_regex='^[0-9]+\.[0-9]+\.[0-9]+$'
+          if [[ ! "${{ github.event.inputs.semver }}" =~ $semver_regex ]]; then
+            echo "Invalid semver format. Please provide a valid semver (e.g., 1.2.3)."
+            exit 1
+          fi
+
       - name: Checkout code 
         uses: actions/checkout@v4
 
@@ -78,7 +93,12 @@ jobs:
 
       # Pack Nuget Package to /artifacts folder for publishing 
       - name: Pack NuGet package
+        if: github.event_name != 'workflow_dispatch'
         run: dotnet pack --configuration Release --output ./artifacts
+
+      - name: Pack NuGet package
+        if: github.event_name == 'workflow_dispatch'
+        run: dotnet pack --configuration Release --output ./artifacts /version=${{ github.event.inputs.semver }}
 
       # Upload NugetPackage as Artifact to workflow
       - name: Upload NuGet package to Artifacts collection
